### ISSUE TITLE
Should "reports" be a map?

### ISSUE THREAD

**Issue by jclem** [bryanmacfarlane/project-reports-action#47]
Since we output the "reports" each in a directory with the name of the report, I'm wondering if we should transition "reports" in the config from a list:

```yaml
reports:
  - name: Todo
    title: etc
  - name: Issues
    title: etc
```

To a map:

```yaml
reports:
  Todo:
    title: etc
  Issues:
    title: etc
```

This would enforce the uniqueness of names, which is currently implicit.
